// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBskDA8gOfZlYOL0FoMkXO9GHeeh6RGGQ8',
    appId: '1:466878923935:web:4d896cfaa8825b34e88eaa',
    messagingSenderId: '466878923935',
    projectId: 'summarizer-521cb',
    authDomain: 'summarizer-521cb.firebaseapp.com',
    storageBucket: 'summarizer-521cb.appspot.com',
    measurementId: 'G-N59N1ZGDY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUSSneQkZQq0kwT4MwvXqqVHlOniNwQVI',
    appId: '1:466878923935:android:d82ee13caa8081f8e88eaa',
    messagingSenderId: '466878923935',
    projectId: 'summarizer-521cb',
    storageBucket: 'summarizer-521cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAki2xE55kp9Sk6eRNZGgj8hT6dPdsly3k',
    appId: '1:466878923935:ios:e4763f7a7b38a88ce88eaa',
    messagingSenderId: '466878923935',
    projectId: 'summarizer-521cb',
    storageBucket: 'summarizer-521cb.appspot.com',
    iosBundleId: 'com.example.summarizerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAki2xE55kp9Sk6eRNZGgj8hT6dPdsly3k',
    appId: '1:466878923935:ios:e4763f7a7b38a88ce88eaa',
    messagingSenderId: '466878923935',
    projectId: 'summarizer-521cb',
    storageBucket: 'summarizer-521cb.appspot.com',
    iosBundleId: 'com.example.summarizerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBskDA8gOfZlYOL0FoMkXO9GHeeh6RGGQ8',
    appId: '1:466878923935:web:7fbedadbae690309e88eaa',
    messagingSenderId: '466878923935',
    projectId: 'summarizer-521cb',
    authDomain: 'summarizer-521cb.firebaseapp.com',
    storageBucket: 'summarizer-521cb.appspot.com',
    measurementId: 'G-Y1SHRRCT9Q',
  );
}
